### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by TheEvilSkeleton** [Lucchetto/SuperImage#1]
Since this app is FOSS, can it be published on [F-Droid](https://f-droid.org/)?

**Comment by Lucchetto** [comment]
Hi, the app was approved on f-droid yesterday, but it hasn't showed up yet. Here is the merge request on f-droid https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12587

**Comment by TheEvilSkeleton** [comment]
Admittedly, I didn't check in the merge request, so my apologies :sweat: Thanks for letting me know.
