### ISSUE TITLE
Rename the 4x and 8x scale factors to 2x and 4x, respectively 

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [Lucchetto/SuperImage#15]
Usually scale factors describe the scale of only one side of the image, not the whole image. Also, even if you want to describe the size of the whole image, it should be 16x, not 8x

**Comment by VasilisKos** [comment]
I disagree. When you double both the sides of an image you actually get the whole image 4 times, and respectively the case with x8. The currently used scale is fine.
