### ISSUE TITLE
Notification info request

### ISSUE THREAD

**Issue by VasilisKos** [Lucchetto/SuperImage#19]
Is it possible to add to the notification the remaining time of the upscale process? That would be very handy.

**Comment by Lucchetto** [comment]
Oh yes that makes a lot of sense. I'll add in the next release

**Comment by VasilisKos** [comment]
Thanks for adding in version 1.3, but the estimated completion time is not viewable in the notification. The overall text is too much to be in one line, as you can see in the attached screenshot.
Is it possible to put the estimated time text in a second line in the notification?

![Screenshot_20230309-221318_1](https://user-images.githubusercontent.com/12777771/224131352-0c763a55-570a-4030-bc43-2bd3acce0a03.png)

**Comment by Lucchetto** [comment]
Ah, on newer android versions it's shown on a separate line. I'll check if it can be fixed

**Comment by VasilisKos** [comment]
> Ah, on newer android versions it's shown on a separate line. I'll check if it can be fixed

I guess you mean newer than Android 11.

**Comment by VasilisKos** [comment]
Also, another good notification enhancement would be the addition of a "cancel" button in the notification.

**Comment by Lucchetto** [comment]
Ahaha, I actually added it then reverted the commit.
I thought it may lead to accidental cancellations

**Comment by VasilisKos** [comment]
> Ahaha, I actually added it then reverted the commit. I thought it may lead to accidental cancellations

Noooo! Bring it back! 😁
