### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [Lucchetto/SuperImage#2]
Please add the themed icon.

![Screenshot_2023-02-21-12-39-40-506_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/220299976-d4f929c1-4e88-401c-83ba-090b6a934409.jpg)

**Comment by Lucchetto** [comment]
ok 👌

**Comment by VasilisKos** [comment]
I think using the notification icon as the drawer app icon would be much better than the now used "S" icon.

**Comment by xmha97** [comment]
Thanks 👍
