### ISSUE TITLE
App crashes while upscaling

### ISSUE THREAD

**Issue by IMXEren** [Lucchetto/SuperImage#21]
The app crashes while upscaling. I tried to reinstall it from different sources i.e.play store, f-droid, GitHub but the issue persists. 

Device Info -
Device: RED8BEL1    
Model: realme RMX3561   
Android: 13

Logs - [logcat_03-01-2023_16-35-57.txt](https://github.com/Lucchetto/SuperImage/files/10860262/logcat_03-01-2023_16-35-57.txt)

Screenshots of Logs - ![Screenshot_2023-03-01-16-50-43-76](https://user-images.githubusercontent.com/96839938/222125285-57d6554a-727d-4148-ac8e-72735f2b8bd4.jpg)

**Comment by Lucchetto** [comment]
Hi, are you upscaling a very small image ?

**Comment by IMXEren** [comment]
Yes, one with (150 x 60) px. Tried a different one just now & it worked, thanks!

**Comment by Lucchetto** [comment]
Reopening as memo
