### ISSUE TITLE
does not work on moto e7 (64gb 4Ram) - mediatek g25

### ISSUE THREAD

**Issue by Sukii23** [Lucchetto/SuperImage#35]
when you press to make the image it starts to load and takes a while, when "0" appears the application closes

**Comment by Lucchetto** [comment]
Are you running latest version ?

**Comment by Sukii23** [comment]
Yes

**Comment by Sukii23** [comment]
Yes

**Comment by Lucchetto** [comment]
If you are running f-droid or GitHub version, please submit the logcat of crash

**Comment by Sukii23** [comment]
# #[Logs](https://drive.proton.me/urls/TVVG80MFFW#DXIUDMbXUDdD) 

everything is alright? this is the first time i have contact with logcat

**Comment by Lucchetto** [comment]
Hi, seems like there are some issues with the OpenCL libraries of your device. I'll check if there is anything I can do on app side
