### ISSUE TITLE
Import image bug

### ISSUE THREAD

**Issue by VasilisKos** [Lucchetto/SuperImage#4]
Tapping the "Select image" button opens the default Android image picker. If you choose the option it has to select an image through one of the available apps on the top (see the red arrow in the attached screenshot), doesn't work. The respective app opens, but selecting an image doesn't import it. 
Using a Nokia 6.2 with Android 11.

![Screenshot_20230221-175325_1](https://user-images.githubusercontent.com/12777771/220381392-2c20600c-827b-450b-9ab1-e8446ed66af9.png)

**Comment by Lucchetto** [comment]
Hi, thanks for reporting. I'll look into it

**Comment by Lucchetto** [comment]
Unfortunately it seems like a bug of Android, so I'll probably just remove the option to select from gallery in file manager

**Comment by VasilisKos** [comment]
> Unfortunately it seems like a bug of Android, so I'll probably just remove the option to select from gallery in file manager

Well I'm not sure about that. Because this doesn't happen with other apps I got installed, that use this way of image selection, like e.g. OpenScan (https://github.com/ethereal-developers/OpenScan), and PicSay Pro.

**Comment by VasilisKos** [comment]
Bug is fixed in version 1.2.2! Thanks!
