### ISSUE TITLE
Can't find resource for bundle java.util.PropertyResourceBundIe, kеу hour.few

### ISSUE THREAD

**Issue by astronom-v-cube** [Lucchetto/SuperImage#51]
When I try to launch in any form, I get an error
![image](https://github.com/Lucchetto/SuperImage/assets/63924364/9ef1d764-3eaa-4857-9931-d019515ac067)
windows 11, amd r5 5600g, 64x

**Comment by Lucchetto** [comment]
Hi, I just fixed it. Will release build in the weekend

**Comment by Lucchetto** [comment]
For now you can set the computer in English as a workaround

**Comment by astronom-v-cube** [comment]
Thank you very much!
