### ISSUE TITLE
Desktop version out?

### ISSUE THREAD

**Issue by NoExplorer** [Lucchetto/SuperImage#52]
I've been looking recently for the desktop version, and I came across a website that does have it, but I'm not sure if it is the official one (seeing that there's no package of it in the repository here)

https://superimage.io/ 

That's all. App works good on phones, one pf the best utility apps I got installed. Keep up the good work!

**Comment by Turhvjbufv** [comment]
Official one pretty sure, take a look at the telegram channel

**Comment by NoExplorer** [comment]
> Official one pretty sure, take a look at the telegram channel

Thanks, I don't have telegram but I will check it out. Was confused that a package wasn't uploaded here.
