### ISSUE TITLE
App font issue

### ISSUE THREAD

**Issue by VasilisKos** [Lucchetto/SuperImage#9]
Would it be possible to use a more "universal" font for the app? Because the currently used one has an issue in the Greek translation that's been recently added. The Greek letter "μ" appears like of another font. Check below. 

![Screenshot_20230223-133544](https://user-images.githubusercontent.com/12777771/220884391-17e4b2ba-a776-437a-b55a-380008f1aaeb.png)

**Comment by Lucchetto** [comment]
Hi, thank you for reporting. I'll look for another font that supports greek characters too
